"""
Omni-InfoFlow Core Data Protocols
==================================
All data flowing through the pipeline is carried by these four types:

- WorkflowItem  : the universal payload — one object walks the entire pipeline
- PluginResult  : every plugin returns this wrapper (success/fail + logs + metrics)
- NodeEvent     : structured event emitted at each pipeline step for observability
- RunContext    : per-run shared context injected into every plugin
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# WorkflowItem — the universal data carrier
# ---------------------------------------------------------------------------

class WorkflowItem(BaseModel):
    """Unified payload traversing every pipeline node.

    Layers:
        - identity  : id, source_type, source_uri
        - raw input : raw_content (bytes or text from source)
        - cleaned   : cleaned_text (normalised by parser)
        - enriched  : summary (generated by AI)
        - artifacts : arbitrary file paths keyed by purpose
                      e.g. {"audio": "/tmp/run-xxx/out.mp3"}
        - status    : per-step status dict filled by the engine
        - metadata  : open-ended extra data attached by any plugin
    """

    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    source_type: str = ""
    source_uri: str = ""
    title: str | None = None

    # ── content layers ──
    raw_content: str | None = None
    cleaned_text: str | None = None
    summary: str | None = None

    # ── extensible bags ──
    metadata: dict[str, Any] = Field(default_factory=dict)
    artifacts: dict[str, Any] = Field(default_factory=dict)
    status: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# PluginResult — normalised return envelope
# ---------------------------------------------------------------------------

class PluginResult(BaseModel):
    """Every plugin returns this so the engine never has to guess the shape."""

    success: bool
    item: WorkflowItem
    logs: list[str] = Field(default_factory=list)
    metrics: dict[str, Any] = Field(default_factory=dict)
    error: str | None = None


# ---------------------------------------------------------------------------
# NodeEvent — structured telemetry for the dashboard
# ---------------------------------------------------------------------------

class NodeEvent(BaseModel):
    """Emitted by the engine at each step boundary.

    The frontend consumes a stream of these to render a real-time pipeline
    visualisation with colour-coded step statuses and timing data.
    """

    run_id: str
    item_id: str
    step: str
    plugin_name: str
    status: Literal["started", "success", "failed", "skipped"]
    message: str = ""
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    duration_ms: int | None = None
    extra: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# RunContext — per-execution shared state
# ---------------------------------------------------------------------------

class RunContext(BaseModel):
    """Injected into every plugin so they never resort to global variables.

    Holds a snapshot of the active config, a dedicated temp directory for
    file I/O, and a mutable ``variables`` bag for inter-plugin communication
    that the engine mediates.
    """

    run_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    config_snapshot: dict[str, Any] = Field(default_factory=dict)
    started_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    temp_dir: str = ""
    variables: dict[str, Any] = Field(default_factory=dict)
